// Generated by gencpp from file auvsi16/ImageProcessing.msg
// DO NOT EDIT!


#ifndef AUVSI16_MESSAGE_IMAGEPROCESSING_H
#define AUVSI16_MESSAGE_IMAGEPROCESSING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auvsi16
{
template <class ContainerAllocator>
struct ImageProcessing_
{
  typedef ImageProcessing_<ContainerAllocator> Type;

  ImageProcessing_()
    : buoy_number(0)
    , center_buoy_x(0)
    , center_buoy_y(0)
    , buoy_area(0)
    , radius_buoy(0)
    , detection_status(false)  {
    }
  ImageProcessing_(const ContainerAllocator& _alloc)
    : buoy_number(0)
    , center_buoy_x(0)
    , center_buoy_y(0)
    , buoy_area(0)
    , radius_buoy(0)
    , detection_status(false)  {
    }



   typedef int32_t _buoy_number_type;
  _buoy_number_type buoy_number;

   typedef int32_t _center_buoy_x_type;
  _center_buoy_x_type center_buoy_x;

   typedef int32_t _center_buoy_y_type;
  _center_buoy_y_type center_buoy_y;

   typedef int32_t _buoy_area_type;
  _buoy_area_type buoy_area;

   typedef int32_t _radius_buoy_type;
  _radius_buoy_type radius_buoy;

   typedef uint8_t _detection_status_type;
  _detection_status_type detection_status;




  typedef boost::shared_ptr< ::auvsi16::ImageProcessing_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auvsi16::ImageProcessing_<ContainerAllocator> const> ConstPtr;

}; // struct ImageProcessing_

typedef ::auvsi16::ImageProcessing_<std::allocator<void> > ImageProcessing;

typedef boost::shared_ptr< ::auvsi16::ImageProcessing > ImageProcessingPtr;
typedef boost::shared_ptr< ::auvsi16::ImageProcessing const> ImageProcessingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auvsi16::ImageProcessing_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auvsi16::ImageProcessing_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auvsi16

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/indigo/share/mavros_msgs/cmake/../msg'], 'auvsi16': ['/home/aldwinakbar/Dropbox/Projects/campus/team/TRUI/amvui2015/AI/src/auvsi16/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auvsi16::ImageProcessing_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auvsi16::ImageProcessing_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auvsi16::ImageProcessing_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auvsi16::ImageProcessing_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auvsi16::ImageProcessing_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auvsi16::ImageProcessing_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auvsi16::ImageProcessing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ff3d57280d166d6d98513c0249ee9a4";
  }

  static const char* value(const ::auvsi16::ImageProcessing_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ff3d57280d166d6ULL;
  static const uint64_t static_value2 = 0xd98513c0249ee9a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::auvsi16::ImageProcessing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auvsi16/ImageProcessing";
  }

  static const char* value(const ::auvsi16::ImageProcessing_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auvsi16::ImageProcessing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 buoy_number\n\
int32 center_buoy_x\n\
int32 center_buoy_y\n\
int32 buoy_area\n\
int32 radius_buoy\n\
bool detection_status\n\
";
  }

  static const char* value(const ::auvsi16::ImageProcessing_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auvsi16::ImageProcessing_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.buoy_number);
      stream.next(m.center_buoy_x);
      stream.next(m.center_buoy_y);
      stream.next(m.buoy_area);
      stream.next(m.radius_buoy);
      stream.next(m.detection_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ImageProcessing_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auvsi16::ImageProcessing_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auvsi16::ImageProcessing_<ContainerAllocator>& v)
  {
    s << indent << "buoy_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.buoy_number);
    s << indent << "center_buoy_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_buoy_x);
    s << indent << "center_buoy_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_buoy_y);
    s << indent << "buoy_area: ";
    Printer<int32_t>::stream(s, indent + "  ", v.buoy_area);
    s << indent << "radius_buoy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.radius_buoy);
    s << indent << "detection_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detection_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUVSI16_MESSAGE_IMAGEPROCESSING_H
