// Generated by gencpp from file auvsi16/overrideMotorRC.msg
// DO NOT EDIT!


#ifndef AUVSI16_MESSAGE_OVERRIDEMOTORRC_H
#define AUVSI16_MESSAGE_OVERRIDEMOTORRC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auvsi16
{
template <class ContainerAllocator>
struct overrideMotorRC_
{
  typedef overrideMotorRC_<ContainerAllocator> Type;

  overrideMotorRC_()
    : steering(0)
    , throttle(0)  {
    }
  overrideMotorRC_(const ContainerAllocator& _alloc)
    : steering(0)
    , throttle(0)  {
    }



   typedef int16_t _steering_type;
  _steering_type steering;

   typedef int16_t _throttle_type;
  _throttle_type throttle;




  typedef boost::shared_ptr< ::auvsi16::overrideMotorRC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auvsi16::overrideMotorRC_<ContainerAllocator> const> ConstPtr;

}; // struct overrideMotorRC_

typedef ::auvsi16::overrideMotorRC_<std::allocator<void> > overrideMotorRC;

typedef boost::shared_ptr< ::auvsi16::overrideMotorRC > overrideMotorRCPtr;
typedef boost::shared_ptr< ::auvsi16::overrideMotorRC const> overrideMotorRCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auvsi16::overrideMotorRC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auvsi16::overrideMotorRC_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auvsi16

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/indigo/share/mavros_msgs/cmake/../msg'], 'auvsi16': ['/home/aldwinakbar/Dropbox/Projects/campus/team/TRUI/amvui2015/AI/src/auvsi16/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auvsi16::overrideMotorRC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auvsi16::overrideMotorRC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auvsi16::overrideMotorRC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auvsi16::overrideMotorRC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auvsi16::overrideMotorRC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auvsi16::overrideMotorRC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auvsi16::overrideMotorRC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4dd5817de7802d91e66008f92eca79e";
  }

  static const char* value(const ::auvsi16::overrideMotorRC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4dd5817de7802d9ULL;
  static const uint64_t static_value2 = 0x1e66008f92eca79eULL;
};

template<class ContainerAllocator>
struct DataType< ::auvsi16::overrideMotorRC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auvsi16/overrideMotorRC";
  }

  static const char* value(const ::auvsi16::overrideMotorRC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auvsi16::overrideMotorRC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 steering\n\
int16 throttle\n\
";
  }

  static const char* value(const ::auvsi16::overrideMotorRC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auvsi16::overrideMotorRC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering);
      stream.next(m.throttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct overrideMotorRC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auvsi16::overrideMotorRC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auvsi16::overrideMotorRC_<ContainerAllocator>& v)
  {
    s << indent << "steering: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steering);
    s << indent << "throttle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.throttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUVSI16_MESSAGE_OVERRIDEMOTORRC_H
