// Generated by gencpp from file auvsi16/RobosubLauncher.msg
// DO NOT EDIT!


#ifndef AUVSI16_MESSAGE_ROBOSUBLAUNCHER_H
#define AUVSI16_MESSAGE_ROBOSUBLAUNCHER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auvsi16
{
template <class ContainerAllocator>
struct RobosubLauncher_
{
  typedef RobosubLauncher_<ContainerAllocator> Type;

  RobosubLauncher_()
    : motor_direction(0)
    , motor_speed(0)
    , launcher_heater(false)  {
    }
  RobosubLauncher_(const ContainerAllocator& _alloc)
    : motor_direction(0)
    , motor_speed(0)
    , launcher_heater(false)  {
    }



   typedef uint8_t _motor_direction_type;
  _motor_direction_type motor_direction;

   typedef uint8_t _motor_speed_type;
  _motor_speed_type motor_speed;

   typedef uint8_t _launcher_heater_type;
  _launcher_heater_type launcher_heater;




  typedef boost::shared_ptr< ::auvsi16::RobosubLauncher_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auvsi16::RobosubLauncher_<ContainerAllocator> const> ConstPtr;

}; // struct RobosubLauncher_

typedef ::auvsi16::RobosubLauncher_<std::allocator<void> > RobosubLauncher;

typedef boost::shared_ptr< ::auvsi16::RobosubLauncher > RobosubLauncherPtr;
typedef boost::shared_ptr< ::auvsi16::RobosubLauncher const> RobosubLauncherConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auvsi16::RobosubLauncher_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auvsi16::RobosubLauncher_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auvsi16

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/indigo/share/mavros_msgs/cmake/../msg'], 'auvsi16': ['/home/aldwinakbar/Dropbox/Projects/campus/team/TRUI/amvui2015/AI/src/auvsi16/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auvsi16::RobosubLauncher_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auvsi16::RobosubLauncher_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auvsi16::RobosubLauncher_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auvsi16::RobosubLauncher_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auvsi16::RobosubLauncher_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auvsi16::RobosubLauncher_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auvsi16::RobosubLauncher_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e49e391094591d98b7d658e6aca54cc1";
  }

  static const char* value(const ::auvsi16::RobosubLauncher_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe49e391094591d98ULL;
  static const uint64_t static_value2 = 0xb7d658e6aca54cc1ULL;
};

template<class ContainerAllocator>
struct DataType< ::auvsi16::RobosubLauncher_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auvsi16/RobosubLauncher";
  }

  static const char* value(const ::auvsi16::RobosubLauncher_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auvsi16::RobosubLauncher_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 motor_direction\n\
uint8 motor_speed\n\
bool launcher_heater\n\
";
  }

  static const char* value(const ::auvsi16::RobosubLauncher_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auvsi16::RobosubLauncher_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_direction);
      stream.next(m.motor_speed);
      stream.next(m.launcher_heater);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RobosubLauncher_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auvsi16::RobosubLauncher_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auvsi16::RobosubLauncher_<ContainerAllocator>& v)
  {
    s << indent << "motor_direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_direction);
    s << indent << "motor_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_speed);
    s << indent << "launcher_heater: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.launcher_heater);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUVSI16_MESSAGE_ROBOSUBLAUNCHER_H
