// Generated by gencpp from file auvsi16/sonarData.msg
// DO NOT EDIT!


#ifndef AUVSI16_MESSAGE_SONARDATA_H
#define AUVSI16_MESSAGE_SONARDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auvsi16
{
template <class ContainerAllocator>
struct sonarData_
{
  typedef sonarData_<ContainerAllocator> Type;

  sonarData_()
    : data()  {
      data.assign(0);
  }
  sonarData_(const ContainerAllocator& _alloc)
    : data()  {
      data.assign(0);
  }



   typedef boost::array<uint16_t, 13>  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::auvsi16::sonarData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auvsi16::sonarData_<ContainerAllocator> const> ConstPtr;

}; // struct sonarData_

typedef ::auvsi16::sonarData_<std::allocator<void> > sonarData;

typedef boost::shared_ptr< ::auvsi16::sonarData > sonarDataPtr;
typedef boost::shared_ptr< ::auvsi16::sonarData const> sonarDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auvsi16::sonarData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auvsi16::sonarData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auvsi16

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/indigo/share/mavros_msgs/cmake/../msg'], 'auvsi16': ['/home/aldwinakbar/Dropbox/Projects/campus/team/TRUI/amvui2015/AI/src/auvsi16/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auvsi16::sonarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auvsi16::sonarData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auvsi16::sonarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auvsi16::sonarData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auvsi16::sonarData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auvsi16::sonarData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auvsi16::sonarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02fbb5521aaac1e6a77790f6244b5c32";
  }

  static const char* value(const ::auvsi16::sonarData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02fbb5521aaac1e6ULL;
  static const uint64_t static_value2 = 0xa77790f6244b5c32ULL;
};

template<class ContainerAllocator>
struct DataType< ::auvsi16::sonarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auvsi16/sonarData";
  }

  static const char* value(const ::auvsi16::sonarData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auvsi16::sonarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[13] data\n\
";
  }

  static const char* value(const ::auvsi16::sonarData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auvsi16::sonarData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct sonarData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auvsi16::sonarData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auvsi16::sonarData_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUVSI16_MESSAGE_SONARDATA_H
