# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from auvsi16/differential_controller.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class differential_controller(genpy.Message):
  _md5sum = "365461bcf44bdfbb44bee48829b6d0e9"
  _type = "auvsi16/differential_controller"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 left_pwm
int16 right_pwm
bool override_apm

"""
  __slots__ = ['left_pwm','right_pwm','override_apm']
  _slot_types = ['int16','int16','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_pwm,right_pwm,override_apm

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(differential_controller, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_pwm is None:
        self.left_pwm = 0
      if self.right_pwm is None:
        self.right_pwm = 0
      if self.override_apm is None:
        self.override_apm = False
    else:
      self.left_pwm = 0
      self.right_pwm = 0
      self.override_apm = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2hB.pack(_x.left_pwm, _x.right_pwm, _x.override_apm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.left_pwm, _x.right_pwm, _x.override_apm,) = _struct_2hB.unpack(str[start:end])
      self.override_apm = bool(self.override_apm)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2hB.pack(_x.left_pwm, _x.right_pwm, _x.override_apm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.left_pwm, _x.right_pwm, _x.override_apm,) = _struct_2hB.unpack(str[start:end])
      self.override_apm = bool(self.override_apm)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2hB = struct.Struct("<2hB")
