# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from auvsi16/RobosubLauncher.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobosubLauncher(genpy.Message):
  _md5sum = "e49e391094591d98b7d658e6aca54cc1"
  _type = "auvsi16/RobosubLauncher"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 motor_direction
uint8 motor_speed
bool launcher_heater

"""
  __slots__ = ['motor_direction','motor_speed','launcher_heater']
  _slot_types = ['uint8','uint8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motor_direction,motor_speed,launcher_heater

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobosubLauncher, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.motor_direction is None:
        self.motor_direction = 0
      if self.motor_speed is None:
        self.motor_speed = 0
      if self.launcher_heater is None:
        self.launcher_heater = False
    else:
      self.motor_direction = 0
      self.motor_speed = 0
      self.launcher_heater = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.motor_direction, _x.motor_speed, _x.launcher_heater))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.motor_direction, _x.motor_speed, _x.launcher_heater,) = _struct_3B.unpack(str[start:end])
      self.launcher_heater = bool(self.launcher_heater)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.motor_direction, _x.motor_speed, _x.launcher_heater))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.motor_direction, _x.motor_speed, _x.launcher_heater,) = _struct_3B.unpack(str[start:end])
      self.launcher_heater = bool(self.launcher_heater)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B = struct.Struct("<3B")
