(cl:defpackage auvsi16-msg
  (:use )
  (:export
   "<ROBOSUBLAUNCHER>"
   "ROBOSUBLAUNCHER"
   "<HSVVALUE>"
   "HSVVALUE"
   "<SONARDATA>"
   "SONARDATA"
   "<OVERRIDEMOTORRC>"
   "OVERRIDEMOTORRC"
   "<IMAGEPROCESSING>"
   "IMAGEPROCESSING"
   "<DIFFERENTIAL_CONTROLLER>"
   "DIFFERENTIAL_CONTROLLER"
  ))

